# Generated by Django 3.2.7 on 2021-11-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewForm',
            new_name='Review',
        ),
    ]
